### ISSUE TITLE
Cross-platform support?

### ISSUE THREAD

**Issue by neuromancer** [tsny/ProjectLonestar#1]
You re-implementation of Freelancer looks really good. I was wondering if you could provide builds for Linux and MacOS (using the Unity engine).

Thanks!

**Comment by tsny** [comment]
I haven't tried this yet so I will try!

**Comment by neuromancer** [comment]
Any luck?

**Comment by tsny** [comment]
I have been a bit busy lately but I am going to have some free time over Thanksgiving so I will make it a point to push an OSX build as I will be able to test on a Mac!

**Comment by tsny** [comment]
Hey, I was recently able to get around to this and there is a build up on the[ itch.io page](https://tsny.itch.io/project-lonestar) for a mac build. I don't think weapons are working as I didn't leave it in a working state since I last developed in November. I'll try and improve it!
